{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "httpbin.serviceAccountName" . }}
  labels:
{{ include "httpbin.labels" . | nindent 4 }}
{{- end -}}
