version: 2.1

job-defaults: &job-defaults
  working_directory: &working_directory
                       ~/app

machine-setup: &machine-setup
  machine:
    docker_layer_caching: false
    image: ubuntu-2204:2023.10.1

setup-env: &setup-env
  run:
    name: Setup Environment
    command: |
      source ./ops/setup-aws-config.sh
      echo 'unset AWS_ACCESS_KEY_ID' >> $BASH_ENV
      echo 'unset AWS_SECRET_ACCESS_KEY' >> $BASH_ENV 
      echo 'export AWS_ACCOUNT_ID=$AWS_PRESIDIO_VAULT_ACCOUNT_ID' >> $BASH_ENV
      echo 'export AWS_REGION=us-east-1' >> $BASH_ENV
      echo 'export VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}' >> $BASH_ENV    

persist-workspace: &persist-workspace
  persist_to_workspace:
    root: .
    paths:
      - "*"

attach-workspace: &attach-workspace
  attach_workspace:
    at: *working_directory

jobs:
  build:
    <<: *machine-setup
    <<: *job-defaults
    steps:
      - checkout
      - <<: *setup-env
      - run: |
          docker-compose build httpbin
          ./ops/docker-save.sh
      - <<: *persist-workspace

#  TODO: Here should be some test as well to verify that container is actually starting in the image and can respond to basic commands

  deploy-image:
    <<: *machine-setup
    <<: *job-defaults
    steps:
      - <<: *attach-workspace
      - <<: *setup-env
      - run: |
          ./ops/docker-login.sh
          ./ops/docker-load.sh
          docker-compose push httpbin

workflows:
  build-test-and-deploy:
    jobs:
      - build:
          context:
            - circleci
            - aws-accounts
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy-image:
          context:
            - circleci
            - aws-accounts
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+(?:-\w+){0,1}$/
            branches:
              ignore: /.*/
